services:
  - type: web
    name: lostfound-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://aditidb:password123456789@aiafsd.syayilb.mongodb.net/lostfound?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_super_secret_key_change_this_in_production_123456
      - key: NODE_ENV
        value: production
